"""Machines whose speaker pin upstream reroutes off a widget with no volume amp.

The class next door to the hidden-pin one: here the pin exists and the BIOS
declares it correctly, so nothing looks wrong, but the codec routes it to a
widget carrying no volume amplifier — upstream's word for the ALC298 case is
that the node "does not has Amp-out capability". That speaker then sits at a
fixed level while every volume and tuning change moves the others, which on a
two-way machine is heard as a woofer that stays barely audible. The kernel
fixes it per machine with an ``snd_hda_override_conn_list`` or a
``preferred_dacs`` pair (``alc285_fixup_speaker2_to_dac1`` is the plain shape),
keyed by subsystem id — so the only way to know a *given* machine needs it is
to carry upstream's list. The design record is ``docs/design-notes.md``, "The
class next door".

Machine-written: ``tools/update_speaker_route_quirks.py`` rebuilds the literal
below from the kernel's Realtek quirk table and the weekly
``.github/workflows/speaker-quirks.yml`` opens a PR when it changes. The
updater finds the table by a regex pinned to its exact shape — including the
``RouteQuirk(...)`` call, keyword arguments and all — so the rendered form is a
contract, not a style choice; ``tests/test_speaker_route_quirks.py`` asserts
the updater re-renders what ships here byte-for-byte.

``RouteQuirk`` lives here rather than beside the code that reads it because the
rows *are* ``RouteQuirk`` calls: a machine rewrite of this file rewrites the
constructor call too, so the record and its rows have to move together.

Only the table lives here. Whether a given machine's pin is actually routed
the wrong way today, and what the user is told about it, stay in
``lib/hardware/speakers.py``, out of reach of the weekly rewrite.

Stdlib-only.
"""

from typing import NamedTuple


class RouteQuirk(NamedTuple):
    """One machine's upstream speaker-route fixup, as generated into the table."""
    model: str        # hda_model= string that forces the fixup, or "" when the
                      # quirk reaches the helper through an unnamed wrapper —
                      # the common case here. Never substitute the inner
                      # fixup's name: forcing alc285-speaker2-to-dac1 on a row
                      # that reaches it via a TAS2781 wrapper would reroute
                      # the pin and skip the amplifier setup.
    pin: str          # the speaker pin the fixup reroutes, e.g. "0x17"
    sources: str      # space-separated widgets the fixup allows that pin to
                      # take signal from, e.g. "0x02" or "0x02 0x03". Widgets,
                      # not DACs: ALC298's fixup targets mixer 0x0c.
    since: str        # oldest released series known to carry the quirk; ""
                      # = mainline-only. Carried forward, never re-derived.
    codec_only: bool  # HDA_CODEC_QUIRK: matched against the codec's
                      # subsystem id only, never the PCI one.


# One row per machine upstream has had to reroute, keyed by subsystem id:
#
#     (subvendor, subdevice): RouteQuirk(model, pin, sources, since, codec_only)
#      └ 0x17AA = Lenovo      └ what `hda_model=` has to be set to, or "" when
#                               the quirk is only reachable through a wrapper
#                               the kernel gives no name — the common case here
#
# and the four qualifiers (see RouteQuirk above for the full meaning): `pin` —
# the speaker pin whose source the fixup overrides, which is the pin to look at
# on a live machine; `sources` — the widgets the fixup lets that pin take signal
# from, all of which have a volume amplifier where the default did not; `since`
# — the kernel series to upgrade to, or "" when no release has it yet, and a
# lower bound rather than the fixup's first release; `codec_only` — upstream
# keys it to the codec's subsystem id, never the PCI one.
#
# Generated by tools/update_speaker_route_quirks.py from upstream's Realtek
# quirk table (weekly, via .github/workflows/speaker-quirks.yml). Which machines
# are listed, and everything about them bar `since`, is rebuilt whole each run
# — a renamed or dropped fixup must not linger here telling users to force a
# quirk their kernel no longer has. `since` is the exception, carried forward
# once derived (see RouteQuirk above). Do not hand-edit.
_SPEAKER_ROUTE_QUIRKS = {
    (0x1028, 0x075C): RouteQuirk("alc298-spk-volume", pin="0x17", sources="0x0c", since="6.11", codec_only=False),
    (0x1028, 0x075D): RouteQuirk("alc298-spk-volume", pin="0x17", sources="0x0c", since="6.11", codec_only=False),
    (0x1028, 0x07B0): RouteQuirk("alc295-disable-dac3", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x1028, 0x097D): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x097E): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0A61): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0A62): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0B19): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0B1A): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0BEB): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0C0B): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0C0D): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0C0E): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0C90): RouteQuirk("", pin="0x17", sources="0x02", since="7.2", codec_only=False),
    (0x1028, 0x0C94): RouteQuirk("", pin="0x17", sources="0x02", since="6.12", codec_only=False),
    (0x1028, 0x0C96): RouteQuirk("", pin="0x17", sources="0x02", since="6.12", codec_only=False),
    (0x1028, 0x0CBD): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0CBE): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0CBF): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0CC0): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0CC1): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0CC2): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0CC3): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0CC4): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1028, 0x0CC5): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x103C, 0x8D18): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.15", codec_only=False),
    (0x103C, 0x8DD4): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.15", codec_only=False),
    (0x103C, 0x8E14): RouteQuirk("", pin="0x17", sources="0x02", since="6.15", codec_only=False),
    (0x103C, 0x8E15): RouteQuirk("", pin="0x17", sources="0x02", since="6.15", codec_only=False),
    (0x103C, 0x8E16): RouteQuirk("", pin="0x17", sources="0x02", since="6.15", codec_only=False),
    (0x103C, 0x8E17): RouteQuirk("", pin="0x17", sources="0x02", since="6.15", codec_only=False),
    (0x103C, 0x8E18): RouteQuirk("", pin="0x17", sources="0x02", since="6.15", codec_only=False),
    (0x103C, 0x8E19): RouteQuirk("", pin="0x17", sources="0x02", since="6.15", codec_only=False),
    (0x103C, 0x8E1A): RouteQuirk("", pin="0x17", sources="0x02", since="6.15", codec_only=False),
    (0x103C, 0x8E1B): RouteQuirk("", pin="0x17", sources="0x02", since="6.15", codec_only=False),
    (0x103C, 0x8E1C): RouteQuirk("", pin="0x17", sources="0x02", since="6.15", codec_only=False),
    (0x103C, 0x8E8A): RouteQuirk("", pin="0x17", sources="0x02", since="6.19", codec_only=False),
    (0x103C, 0x8ED5): RouteQuirk("", pin="0x17", sources="0x02", since="6.19", codec_only=False),
    (0x103C, 0x8ED6): RouteQuirk("", pin="0x17", sources="0x02", since="6.19", codec_only=False),
    (0x103C, 0x8ED7): RouteQuirk("", pin="0x17", sources="0x02", since="6.19", codec_only=False),
    (0x103C, 0x8ED8): RouteQuirk("", pin="0x17", sources="0x02", since="6.19", codec_only=False),
    (0x103C, 0x8ED9): RouteQuirk("", pin="0x17", sources="0x02", since="6.19", codec_only=False),
    (0x103C, 0x8EDA): RouteQuirk("", pin="0x17", sources="0x02", since="6.19", codec_only=False),
    (0x103C, 0x8F40): RouteQuirk("", pin="0x17", sources="0x02", since="6.18", codec_only=False),
    (0x103C, 0x8F41): RouteQuirk("", pin="0x17", sources="0x02", since="6.18", codec_only=False),
    (0x103C, 0x8F42): RouteQuirk("", pin="0x17", sources="0x02", since="6.18", codec_only=False),
    (0x103C, 0x8F62): RouteQuirk("", pin="0x17", sources="0x02", since="6.19", codec_only=False),
    (0x103C, 0x8F7E): RouteQuirk("", pin="0x17", sources="0x02", since="", codec_only=False),
    (0x103C, 0x8F94): RouteQuirk("", pin="0x17", sources="0x02", since="7.2", codec_only=False),
    (0x103C, 0x8F95): RouteQuirk("", pin="0x17", sources="0x02", since="7.2", codec_only=False),
    (0x1043, 0x1024): RouteQuirk("", pin="0x17", sources="0x02", since="6.19", codec_only=False),
    (0x1043, 0x1034): RouteQuirk("", pin="0x17", sources="0x02", since="6.16", codec_only=False),
    (0x1043, 0x1044): RouteQuirk("", pin="0x17", sources="0x02", since="", codec_only=False),
    (0x1043, 0x10A4): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x1043, 0x1154): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x1043, 0x1264): RouteQuirk("", pin="0x15", sources="0x02 0x03", since="6.15", codec_only=False),
    (0x1043, 0x1314): RouteQuirk("", pin="0x17", sources="0x02", since="6.16", codec_only=False),
    (0x1043, 0x1433): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1463): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1473): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1483): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1493): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1573): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1662): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1663): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x16B2): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x17D1): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x17F3): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1970): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1B11): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1B13): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1C52): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1C62): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1C63): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1C9F): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1CAF): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1CEF): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1D42): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1DF3): RouteQuirk("", pin="0x15", sources="0x02 0x03", since="6.13", codec_only=False),
    (0x1043, 0x1E63): RouteQuirk("", pin="0x17", sources="0x02", since="6.13", codec_only=False),
    (0x1043, 0x1E83): RouteQuirk("", pin="0x17", sources="0x02", since="6.13", codec_only=False),
    (0x1043, 0x1E8E): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1EB3): RouteQuirk("", pin="0x17", sources="0x02", since="6.12", codec_only=False),
    (0x1043, 0x1EE2): RouteQuirk("", pin="0x17", sources="0x02", since="", codec_only=False),
    (0x1043, 0x1F11): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x1F92): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x3A20): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x3A30): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x3A40): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x3A50): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x3A60): RouteQuirk("", pin="0x17", sources="0x02", since="6.11", codec_only=False),
    (0x1043, 0x3E30): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x1043, 0x3EE0): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x1043, 0x3EF0): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x1043, 0x3F00): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x1043, 0x3F10): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x1043, 0x3F20): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x1043, 0x3F30): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x2234): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x2292): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x22BE): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x2326): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x3802): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.13", codec_only=False),
    (0x17AA, 0x386E): RouteQuirk("", pin="0x17", sources="0x02", since="6.13", codec_only=False),
    (0x17AA, 0x3870): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x387D): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x387E): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x387F): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x3880): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x3881): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x3884): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x3886): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x38A5): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x38A7): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="7.2", codec_only=True),
    (0x17AA, 0x38A8): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.14", codec_only=True),
    (0x17AA, 0x38B8): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x38B9): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x38BA): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x38BB): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x38BE): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x38BF): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x38C3): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x38CB): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x38CD): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.11", codec_only=False),
    (0x17AA, 0x38D3): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x38D4): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x38D5): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="7.1", codec_only=True),
    (0x17AA, 0x38D6): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="7.1", codec_only=True),
    (0x17AA, 0x38DF): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x38E0): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x38F8): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x38FD): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x3906): RouteQuirk("alc287-lenovo-legion-aw88399", pin="0x17", sources="0x02", since="", codec_only=True),
    (0x17AA, 0x3907): RouteQuirk("alc287-lenovo-legion-aw88399", pin="0x17", sources="0x02", since="", codec_only=True),
    (0x17AA, 0x391F): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x3920): RouteQuirk("", pin="0x17", sources="0x02 0x03", since="6.12", codec_only=False),
    (0x17AA, 0x3927): RouteQuirk("alc287-lenovo-legion-aw88399", pin="0x17", sources="0x02", since="", codec_only=True),
    (0x17AA, 0x3928): RouteQuirk("alc287-lenovo-legion-aw88399", pin="0x17", sources="0x02", since="", codec_only=True),
    (0x17AA, 0x3936): RouteQuirk("alc287-lenovo-legion-aw88399", pin="0x17", sources="0x02", since="", codec_only=True),
    (0x17AA, 0x3937): RouteQuirk("alc287-lenovo-legion-aw88399", pin="0x17", sources="0x02", since="", codec_only=True),
    (0x17AA, 0x3938): RouteQuirk("alc287-lenovo-legion-aw88399", pin="0x17", sources="0x02", since="", codec_only=True),
    (0x17AA, 0x3939): RouteQuirk("alc287-lenovo-legion-aw88399", pin="0x17", sources="0x02", since="", codec_only=True),
    (0x1F4C, 0xE001): RouteQuirk("alc245-fixup-bass-hp-dac", pin="0x17", sources="0x02 0x03", since="7.0", codec_only=False),
    (0x2782, 0x1707): RouteQuirk("alc298-spk-volume", pin="0x17", sources="0x0c", since="6.11", codec_only=False),
}
