"""Machines whose firmware hides a woofer pin, from upstream's fixup table.

Machine-written: ``tools/update_speaker_pin_quirks.py`` rebuilds the literal
below from the kernel's Realtek quirk table and the weekly
``.github/workflows/speaker-pin-quirks.yml`` opens a PR when it changes. The
updater finds the table by a regex pinned to its exact shape — including the
``PinQuirk(...)`` call, keyword arguments and all — so the rendered form is a
contract, not a style choice; ``tests/test_speaker_pin_quirks.py`` asserts the
updater re-renders what ships here byte-for-byte.

``PinQuirk`` lives here rather than beside the code that reads it because the
rows *are* ``PinQuirk`` calls: a machine rewrite of this file rewrites the
constructor call too, so the record and its rows have to move together.

Only the table lives here. Which pin counts as missing, and what the user is
told to do about it, stay in ``lib/hardware/speakers.py``
(``find_hidden_speaker_pin`` and friends), out of reach of the weekly rewrite.

Stdlib-only.
"""

from typing import NamedTuple


class PinQuirk(NamedTuple):
    """One machine's upstream speaker-pin fixup, as generated into the table."""
    model: str        # hda_model= string that forces the fixup, or "" when the
                      # kernel gives it no name and only an upgrade can deliver
                      # it. We never substitute a *related* fixup's name: on the
                      # Yoga 9 14IMH9 that would set the pin and skip the
                      # amplifier setup its chain also does — a half-fix
                      # presented as a fix.
    pins: str         # space-separated pin nodes the fixup declares as internal
                      # speakers, e.g. "0x14 0x17". Any of them missing is the
                      # warning's trigger — see find_hidden_speaker_pin.
    since: str        # oldest released series carrying the quirk, e.g. "7.2";
                      # "" = mainline only, which makes "upgrade" a dead end.
                      # Compared against the running kernel, so a user already
                      # past it is not told to go get what they have.
    codec_only: bool  # HDA_CODEC_QUIRK: matched against the codec's subsystem
                      # id only, never the PCI one


# One row per machine upstream has had to fix, keyed by subsystem id:
#
#     (subvendor, subdevice): PinQuirk(model, pins, since, codec_only)
#      └ 0x17AA = Lenovo      └ what `hda_model=` has to be set to, or "" when
#                               only a kernel upgrade can deliver this fixup
#
# and the three qualifiers, all of which change what the user is told (see
# PinQuirk above for the full meaning): `pins` — the speaker pins this fixup
# declares, any of them missing being what triggers the warning; `since` — the
# kernel series to upgrade to, or "" when no release has it yet; `codec_only`
# — upstream keys it to the codec's subsystem id, never the PCI one.
#
# Generated by tools/update_speaker_pin_quirks.py from upstream's Realtek quirk
# table (weekly, via .github/workflows/speaker-pin-quirks.yml). Rebuilt whole
# each run — a renamed or dropped fixup must not linger here telling users to
# force a quirk their kernel no longer has. Do not hand-edit.
_SPEAKER_PIN_QUIRKS = {
    (0x1025, 0x1177): PinQuirk("", pins="0x17 0x1b", since="6.12", codec_only=False),
    (0x1025, 0x1178): PinQuirk("", pins="0x17 0x1b", since="6.12", codec_only=False),
    (0x1025, 0x1246): PinQuirk("predator-spk", pins="0x21", since="6.11", codec_only=False),
    (0x1028, 0x05DA): PinQuirk("", pins="0x17", since="6.11", codec_only=False),
    (0x1028, 0x0615): PinQuirk("alc290-subwoofer", pins="0x17", since="6.11", codec_only=False),
    (0x1028, 0x0616): PinQuirk("alc290-subwoofer", pins="0x17", since="6.11", codec_only=False),
    (0x1028, 0x069A): PinQuirk("alc290-subwoofer", pins="0x17", since="6.11", codec_only=False),
    (0x1028, 0x0706): PinQuirk("dell-inspiron-7559", pins="0x1b", since="6.11", codec_only=False),
    (0x1028, 0x0798): PinQuirk("dell-inspiron-7559", pins="0x1b", since="6.11", codec_only=False),
    (0x1028, 0x0B37): PinQuirk("", pins="0x14 0x17", since="6.11", codec_only=False),
    (0x1028, 0x0B71): PinQuirk("", pins="0x14 0x17", since="6.11", codec_only=False),
    (0x1028, 0x0C28): PinQuirk("", pins="0x14 0x17", since="6.11", codec_only=False),
    (0x103C, 0x8519): PinQuirk("alc285-hp-spectre-x360", pins="0x14", since="6.11", codec_only=False),
    (0x103C, 0x863E): PinQuirk("alc285-hp-spectre-x360-df1", pins="0x14 0x17", since="6.15", codec_only=False),
    (0x103C, 0x86E7): PinQuirk("alc285-hp-spectre-x360-eb1", pins="0x14 0x17", since="6.11", codec_only=False),
    (0x103C, 0x86E8): PinQuirk("alc285-hp-spectre-x360-eb1", pins="0x14 0x17", since="6.11", codec_only=False),
    (0x103C, 0x8811): PinQuirk("alc285-hp-spectre-x360-eb1", pins="0x14 0x17", since="6.11", codec_only=False),
    (0x103C, 0x8812): PinQuirk("alc285-hp-spectre-x360-eb1", pins="0x14 0x17", since="6.11", codec_only=False),
    (0x103C, 0x89DA): PinQuirk("", pins="0x14 0x17", since="6.18", codec_only=False),
    (0x103C, 0x8C15): PinQuirk("", pins="0x14 0x17", since="6.11", codec_only=False),
    (0x103C, 0x8C16): PinQuirk("", pins="0x14 0x17", since="6.12", codec_only=False),
    (0x103C, 0x8CDD): PinQuirk("", pins="0x14 0x17", since="6.15", codec_only=False),
    (0x103C, 0x8CDE): PinQuirk("", pins="0x14 0x17", since="6.15", codec_only=False),
    (0x1043, 0x1652): PinQuirk("", pins="0x17 0x1e", since="6.18", codec_only=False),
    (0x1043, 0x1CAF): PinQuirk("", pins="0x14", since="6.11", codec_only=False),
    (0x1043, 0x3A20): PinQuirk("", pins="0x14", since="6.11", codec_only=False),
    (0x1043, 0x3A30): PinQuirk("", pins="0x14", since="6.11", codec_only=False),
    (0x1043, 0x3A40): PinQuirk("", pins="0x14", since="6.11", codec_only=False),
    (0x1043, 0x3A50): PinQuirk("", pins="0x14", since="6.11", codec_only=False),
    (0x1043, 0x3A60): PinQuirk("", pins="0x14", since="6.11", codec_only=False),
    (0x17AA, 0x3801): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="6.11", codec_only=False),
    (0x17AA, 0x3869): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="6.11", codec_only=False),
    (0x17AA, 0x386A): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.2", codec_only=True),
    (0x17AA, 0x3882): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="6.11", codec_only=False),
    (0x17AA, 0x3891): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="6.11", codec_only=False),
    (0x17AA, 0x38B1): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.2", codec_only=True),
    (0x17AA, 0x38CF): PinQuirk("", pins="0x17", since="7.0", codec_only=True),
    (0x17AA, 0x38D2): PinQuirk("", pins="0x17", since="6.11", codec_only=False),
    (0x17AA, 0x38D7): PinQuirk("", pins="0x17", since="6.11", codec_only=False),
    (0x17AA, 0x390D): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="6.15", codec_only=False),
    (0x17AA, 0x3911): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.0", codec_only=False),
    (0x17AA, 0x3912): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.2", codec_only=False),
    (0x17AA, 0x391A): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.0", codec_only=False),
    (0x17AA, 0x391C): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="6.18", codec_only=True),
    (0x17AA, 0x391D): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.0", codec_only=True),
    (0x17AA, 0x394C): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.1", codec_only=True),
    (0x1E39, 0xCA14): PinQuirk("", pins="0x1b", since="6.19", codec_only=False),
    (0x2782, 0x0228): PinQuirk("", pins="0x14 0x1b", since="6.12", codec_only=False),
    (0x2782, 0x1701): PinQuirk("", pins="0x1b", since="6.13", codec_only=False),
    (0x2782, 0x1705): PinQuirk("", pins="0x1b", since="6.13", codec_only=False),
    (0x2782, 0x4900): PinQuirk("", pins="0x1b", since="6.13", codec_only=False),
    (0x2782, 0xA212): PinQuirk("", pins="0x1b", since="7.2", codec_only=False),
    (0xC011, 0x1D05): PinQuirk("", pins="0x1b", since="7.2", codec_only=False),
}
