"""Machines whose firmware hides a woofer pin, from upstream's fixup table.

Machine-written: ``tools/update_speaker_pin_quirks.py`` rebuilds the literal
below from the kernel's Realtek quirk table and the weekly
``.github/workflows/speaker-quirks.yml`` opens a PR when it changes. The
updater finds the table by a regex pinned to its exact shape — including the
``PinQuirk(...)`` call, keyword arguments and all — so the rendered form is a
contract, not a style choice; ``tests/test_speaker_pin_quirks.py`` asserts the
updater re-renders what ships here byte-for-byte.

``PinQuirk`` lives here rather than beside the code that reads it because the
rows *are* ``PinQuirk`` calls: a machine rewrite of this file rewrites the
constructor call too, so the record and its rows have to move together.

Only the table lives here. Which pin counts as missing, and what the user is
told to do about it, stay in ``lib/hardware/speakers.py``
(``find_hidden_speaker_pin`` and friends), out of reach of the weekly rewrite.

Stdlib-only.
"""

from typing import NamedTuple


class PinQuirk(NamedTuple):
    """One machine's upstream speaker-pin fixup, as generated into the table."""
    model: str        # hda_model= string that forces the fixup, or "" when the
                      # kernel gives it no name and only an upgrade can deliver
                      # it. We never substitute a *related* fixup's name: on the
                      # Yoga 9 14IMH9 that would set the pin and skip the
                      # amplifier setup its chain also does — a half-fix
                      # presented as a fix.
    pins: str         # space-separated pin nodes the fixup declares as internal
                      # speakers, e.g. "0x14 0x17". Any of them missing is the
                      # warning's trigger — see find_hidden_speaker_pin.
    since: str        # oldest released series *known* to carry the quirk, e.g.
                      # "7.2"; "" = mainline only, which makes "upgrade" a dead
                      # end. Compared against the running kernel, so a user
                      # already past it is not told to go get what they have.
                      # A lower bound, not a birthday: an entry older than the
                      # oldest release the updater walked back to is recorded
                      # as that one. Once recorded it is carried, never
                      # re-derived — a released kernel's contents cannot
                      # change, so a rewrite could only ever lose the answer.
    codec_only: bool  # HDA_CODEC_QUIRK: matched against the codec's subsystem
                      # id only, never the PCI one
    commit: str = ""  # upstream commit that last wrote this entry's line in the
                      # kernel's quirk table (12-hex, from `git blame`), so the
                      # warning can link what it claims. Usually the commit that
                      # added the entry; after an upstream edit of the line, the
                      # edit. "" = not resolved yet, which links the file instead.


# One row per machine upstream has had to fix, keyed by subsystem id:
#
#     (subvendor, subdevice): PinQuirk(model, pins, since, codec_only, commit)
#      └ 0x17AA = Lenovo      └ what `hda_model=` has to be set to, or "" when
#                               only a kernel upgrade can deliver this fixup
#
# and the four qualifiers, all of which change what the user is told (see
# PinQuirk above for the full meaning): `pins` — the speaker pins this fixup
# declares, any of them missing being what triggers the warning; `since` — the
# kernel series to upgrade to, or "" when no release has it yet, and a lower
# bound rather than the fixup's first release; `codec_only` — upstream keys it
# to the codec's subsystem id, never the PCI one; `commit` — the upstream
# commit that last wrote this entry's line, which is what the warning links.
#
# Generated by tools/update_speaker_pin_quirks.py from upstream's Realtek quirk
# table (weekly, via .github/workflows/speaker-quirks.yml). Which machines
# are listed, and everything about them bar `since` and `commit`, is rebuilt
# whole each run — a renamed or dropped fixup must not linger here telling
# users to force a quirk their kernel no longer has. Those two are the
# exception, carried forward once derived (see PinQuirk above). Do not
# hand-edit.
_SPEAKER_PIN_QUIRKS = {
    (0x1025, 0x1177): PinQuirk("", pins="0x17 0x1b", since="6.12", codec_only=False, commit="35fdc6e1c160"),
    (0x1025, 0x1178): PinQuirk("", pins="0x17 0x1b", since="6.12", codec_only=False, commit="35fdc6e1c160"),
    (0x1025, 0x1246): PinQuirk("predator-spk", pins="0x21", since="6.10", codec_only=False, commit="e2a829b3da01"),
    (0x1025, 0x1826): PinQuirk("", pins="0x17 0x1b", since="6.16", codec_only=False, commit="d64cbb5ed922"),
    (0x1025, 0x182C): PinQuirk("", pins="0x17 0x1b", since="6.16", codec_only=False, commit="d64cbb5ed922"),
    (0x1025, 0x1844): PinQuirk("", pins="0x17 0x1b", since="6.16", codec_only=False, commit="d64cbb5ed922"),
    (0x1028, 0x05DA): PinQuirk("", pins="0x17", since="6.10", codec_only=False, commit="0f4881dc1fd8"),
    (0x1028, 0x0615): PinQuirk("alc290-subwoofer", pins="0x17", since="6.10", codec_only=False, commit="0f4881dc1fd8"),
    (0x1028, 0x0616): PinQuirk("alc290-subwoofer", pins="0x17", since="6.10", codec_only=False, commit="0f4881dc1fd8"),
    (0x1028, 0x069A): PinQuirk("alc290-subwoofer", pins="0x17", since="6.10", codec_only=False, commit="3a05d12f46cb"),
    (0x1028, 0x0706): PinQuirk("dell-inspiron-7559", pins="0x1b", since="6.10", codec_only=False, commit="fd06c77eb920"),
    (0x1028, 0x0798): PinQuirk("dell-inspiron-7559", pins="0x1b", since="6.10", codec_only=False, commit="493de342748c"),
    (0x1028, 0x097D): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="e79c22695abd"),
    (0x1028, 0x097E): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="aa143ad39a52"),
    (0x1028, 0x0A61): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="da94692001ea"),
    (0x1028, 0x0A62): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="eb676622846b"),
    (0x1028, 0x0B19): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="15dad62f4bdb"),
    (0x1028, 0x0B1A): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="bdc9b7396f7d"),
    (0x1028, 0x0B37): PinQuirk("", pins="0x14 0x17", since="6.10", codec_only=False, commit="2912cdda734d"),
    (0x1028, 0x0B71): PinQuirk("", pins="0x14 0x17", since="6.10", codec_only=False, commit="2912cdda734d"),
    (0x1028, 0x0BEB): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="cd14dedf15be"),
    (0x1028, 0x0C0B): PinQuirk("", pins="0x14", since="6.11", codec_only=False, commit="fddab35fd064"),
    (0x1028, 0x0C0D): PinQuirk("", pins="0x14", since="6.11", codec_only=False, commit="fcfc9f711d1e"),
    (0x1028, 0x0C0E): PinQuirk("", pins="0x14", since="6.11", codec_only=False, commit="fddab35fd064"),
    (0x1028, 0x0C28): PinQuirk("", pins="0x14 0x17", since="6.10", codec_only=False, commit="89a0dff6105e"),
    (0x1028, 0x0C90): PinQuirk("", pins="0x17", since="7.2", codec_only=False, commit="914c85fad93c"),
    (0x1028, 0x0C94): PinQuirk("", pins="0x17", since="6.17", codec_only=False, commit="ec8f26092e52"),
    (0x1028, 0x0C96): PinQuirk("", pins="0x17", since="6.17", codec_only=False, commit="ec8f26092e52"),
    (0x1028, 0x0CBD): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="f0d9da19d7de"),
    (0x1028, 0x0CBE): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="f0d9da19d7de"),
    (0x1028, 0x0CBF): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="f0d9da19d7de"),
    (0x1028, 0x0CC0): PinQuirk("", pins="0x14", since="6.11", codec_only=False, commit="f0d9da19d7de"),
    (0x1028, 0x0CC1): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="f0d9da19d7de"),
    (0x1028, 0x0CC2): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="f0d9da19d7de"),
    (0x1028, 0x0CC3): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="f0d9da19d7de"),
    (0x1028, 0x0CC4): PinQuirk("", pins="0x17", since="6.11", codec_only=False, commit="f0d9da19d7de"),
    (0x1028, 0x0CC5): PinQuirk("", pins="0x14", since="6.11", codec_only=False, commit="f0d9da19d7de"),
    (0x103C, 0x8519): PinQuirk("alc285-hp-spectre-x360", pins="0x14", since="6.10", codec_only=False, commit="f2be77fee648"),
    (0x103C, 0x85DE): PinQuirk("alc285-hp-envy-x360", pins="0x14 0x17", since="6.11", codec_only=False, commit="c062166995c9"),
    (0x103C, 0x863E): PinQuirk("alc285-hp-spectre-x360-df1", pins="0x14 0x17", since="6.15", codec_only=False, commit="be0c40da8888"),
    (0x103C, 0x86E7): PinQuirk("alc285-hp-spectre-x360-eb1", pins="0x14 0x17", since="6.10", codec_only=False, commit="24df5428ef9d"),
    (0x103C, 0x86E8): PinQuirk("alc285-hp-spectre-x360-eb1", pins="0x14 0x17", since="6.10", codec_only=False, commit="24df5428ef9d"),
    (0x103C, 0x8811): PinQuirk("alc285-hp-spectre-x360-eb1", pins="0x14 0x17", since="6.10", codec_only=False, commit="d94befbb5ae3"),
    (0x103C, 0x8812): PinQuirk("alc285-hp-spectre-x360-eb1", pins="0x14 0x17", since="6.10", codec_only=False, commit="d94befbb5ae3"),
    (0x103C, 0x89DA): PinQuirk("", pins="0x14 0x17", since="6.18", codec_only=False, commit="50a098e3e9b1"),
    (0x103C, 0x8C15): PinQuirk("", pins="0x14 0x17", since="6.10", codec_only=False, commit="61456da04602"),
    (0x103C, 0x8C16): PinQuirk("", pins="0x14 0x17", since="6.12", codec_only=False, commit="557f6e4ab5ba"),
    (0x103C, 0x8C17): PinQuirk("", pins="0x14 0x17", since="", codec_only=False, commit="bfcdc1c0eaea"),
    (0x103C, 0x8CDD): PinQuirk("", pins="0x14 0x17", since="6.15", codec_only=False, commit="494d0939b1bd"),
    (0x103C, 0x8CDE): PinQuirk("", pins="0x14 0x17", since="6.15", codec_only=False, commit="494d0939b1bd"),
    (0x1043, 0x1652): PinQuirk("", pins="0x17 0x1e", since="6.18", codec_only=False, commit="328b80b29a6a"),
    (0x1043, 0x1CAF): PinQuirk("", pins="0x14", since="6.10", codec_only=False, commit="a40ce9f4bdbe"),
    (0x1043, 0x3A20): PinQuirk("", pins="0x14", since="6.11", codec_only=False, commit="e6e18021ddd0"),
    (0x1043, 0x3A30): PinQuirk("", pins="0x14", since="6.11", codec_only=False, commit="e6e18021ddd0"),
    (0x1043, 0x3A40): PinQuirk("", pins="0x14", since="6.10", codec_only=False, commit="2be46155d792"),
    (0x1043, 0x3A50): PinQuirk("", pins="0x14", since="6.11", codec_only=False, commit="e6e18021ddd0"),
    (0x1043, 0x3A60): PinQuirk("", pins="0x14", since="6.10", codec_only=False, commit="0bfe105018bd"),
    (0x17AA, 0x3801): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="6.10", codec_only=False, commit="3790a3d6dbbc"),
    (0x17AA, 0x3869): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="6.10", codec_only=False, commit="70cfdd0365ac"),
    (0x17AA, 0x386A): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.2", codec_only=True, commit="b70f007a9fc6"),
    (0x17AA, 0x3882): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="6.10", codec_only=False, commit="634e5e1e06f5"),
    (0x17AA, 0x3891): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="6.10", codec_only=False, commit="ad22051afdad"),
    (0x17AA, 0x38B1): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.2", codec_only=True, commit="853e10ec4459"),
    (0x17AA, 0x38CF): PinQuirk("", pins="0x17", since="7.0", codec_only=True, commit="217d5bc9f962"),
    (0x17AA, 0x38D2): PinQuirk("", pins="0x17", since="6.10", codec_only=False, commit="9b714a59b719"),
    (0x17AA, 0x38D7): PinQuirk("", pins="0x17", since="6.10", codec_only=False, commit="9b714a59b719"),
    (0x17AA, 0x390D): PinQuirk("", pins="0x17", since="6.15", codec_only=False, commit="42597bb78a34"),
    (0x17AA, 0x3911): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.0", codec_only=False, commit="f0541edb2e73"),
    (0x17AA, 0x3912): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.2", codec_only=False, commit="3a3e810e9108"),
    (0x17AA, 0x391A): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="", codec_only=True, commit="75dc2eda659f"),
    (0x17AA, 0x391C): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="6.18", codec_only=True, commit="1386d16761c0"),
    (0x17AA, 0x391D): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.0", codec_only=True, commit="7bae956cac04"),
    (0x17AA, 0x3926): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="", codec_only=True, commit="9976513eb642"),
    (0x17AA, 0x394C): PinQuirk("alc287-yoga9-bass-spk-pin", pins="0x17", since="7.1", codec_only=True, commit="f7b1f71566ff"),
    (0x1A58, 0x2023): PinQuirk("", pins="0x14 0x17", since="", codec_only=False, commit="61471f29f315"),
    (0x1A58, 0x300E): PinQuirk("", pins="0x14 0x17", since="", codec_only=False, commit="961d9f98da0d"),
    (0x1E39, 0xCA14): PinQuirk("", pins="0x1b", since="6.19", codec_only=False, commit="e64826e5e367"),
    (0x1E50, 0x7036): PinQuirk("", pins="0x1b", since="", codec_only=False, commit="3c6886dec94c"),
    (0x2782, 0x0228): PinQuirk("", pins="0x14 0x1b", since="6.12", codec_only=False, commit="ef5fbdf732a1"),
    (0x2782, 0x1701): PinQuirk("", pins="0x1b", since="6.13", codec_only=False, commit="5ebe792a5139"),
    (0x2782, 0x1705): PinQuirk("", pins="0x1b", since="6.13", codec_only=False, commit="ca0f79f02860"),
    (0x2782, 0x4900): PinQuirk("", pins="0x1b", since="6.13", codec_only=False, commit="31917b7bd892"),
    (0x2782, 0xA212): PinQuirk("", pins="0x1b", since="7.2", codec_only=False, commit="5c3f8dac531b"),
    (0xC011, 0x1D05): PinQuirk("", pins="0x1b", since="7.2", codec_only=False, commit="9064637fb2a8"),
}
