"""The filter-chain conf itself: which stages, wired how, rendered as SPA-JSON.

``build_chain`` walks the preset's ``plugins_order``, hands each key to the
emitter ``lib.pipewire.plugins`` registered for it, and collects the warnings a
skipped or unknown plugin raises. ``emit_links`` pairs the resulting stages
stereo-wise, and ``format_conf`` renders the whole thing — including the
``capture.props`` / ``playback.props`` that decide whether the chain is a
WirePlumber smart filter or a v1 virtual sink.

The SPA-JSON writer is hand-rolled rather than ``json.dumps``-based because
PipeWire's dialect is not JSON: bare keys, ``=`` instead of ``:``, and no
commas. Reading it back is the opposite — ``spa-json-dump`` does that, in
``checks.py``.

``Stage``, ``ChainResult`` and ``EE_KEY_DISPATCH`` come in under their bare
names because none of them holds state a patch would have to reach: two
dataclasses and a table built at import time.

Stdlib-only: ``lib.version`` is the only non-stdlib import, for the ``#
version:`` stamp the conf header carries and ``--doctor`` reads back.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from lib import version
from lib.pipewire.plugins import ChainResult, EE_KEY_DISPATCH, Stage


# First line of every conf this script writes. --doctor keys on it to tell
# our confs from a user's own filter chains, so it must stay in step with the
# header format_conf() emits.
CONF_HEADER_MARK = "# Generated by ee_to_pipewire.py"
DEFAULT_NODE_NAME = "Dolby_Filter_Chain"
DEFAULT_NODE_DESCRIPTION = "Dolby DAX3 (filter-chain)"
DEFAULT_LINK_GROUP_SUFFIX = "_smart_filter"

# Nothing in this module prints it. It lives here because the three that do —
# ``lib.pipewire.install``, ``lib.pipewire.checks`` and ``ee_to_pipewire.py``
# — already import this module, so collapsing the four copies here adds no
# import edge. ``lib.console`` is the other module all three share and the
# wrong home for it: it owns how a line is printed, not the conf vocabulary a
# restart-to-load-it belongs to. ``install`` also runs it, splitting on
# whitespace: keep it a plain argv-shaped string with no shell syntax in it.
PIPEWIRE_RESTART_CMD = "systemctl --user restart pipewire pipewire-pulse"


def _assert_positional(plugins_order: list[str]) -> None:
    """Lock the dialog/PEQ and MBC/regulator disambiguation contracts.

    Both `equalizer#0` (PEQ) and `equalizer#1` (dialog) are emitted by
    `dolby_to_easyeffects.py` with the same dict shape — only their
    position in `plugins_order` distinguishes them. The same is true of
    `multiband_compressor#0` (MBC) and `multiband_compressor#1`
    (regulator). If a future change reordered either pair, the
    converter's mapping would silently swap roles. Fail loudly here.
    """
    # Real raises, not bare asserts — the contract must survive `python -O`.
    for first, role1, second, role2 in (
            ("equalizer#0", "PEQ", "equalizer#1", "dialog"),
            ("multiband_compressor#0", "MBC",
             "multiband_compressor#1", "regulator")):
        if first in plugins_order and second in plugins_order \
                and plugins_order.index(first) >= plugins_order.index(second):
            raise ValueError(
                f"{first} ({role1}) must precede {second} ({role2}) in "
                f"plugins_order; got {plugins_order!r}")


def _sanitize_name(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", name)


def _safe_node_name(stem: str) -> str:
    """Mirror ee_to_pipewire's default node naming (sanitised preset stem)
    so the wrapper can predict conf filenames and PW node names."""
    derived = _sanitize_name(stem).strip("_")
    return derived if derived else DEFAULT_NODE_NAME


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def build_chain(preset: dict, irs_dir: Path,
                must_exist: bool = True) -> ChainResult:
    """Walk plugins_order and build the PW stage list."""
    out = preset.get("output")
    if not isinstance(out, dict):
        raise ValueError("preset has no 'output' object")
    plugins_order = out.get("plugins_order", [])
    _assert_positional(plugins_order)

    result = ChainResult()

    def warn(msg: str) -> None:
        result.warnings.append(msg)

    for key in plugins_order:
        plugin = out.get(key)
        if not isinstance(plugin, dict):
            warn(f"{key}: missing from preset object; skipped.")
            continue

        handler = EE_KEY_DISPATCH.get(key)
        if handler is None:
            warn(f"{key}: unknown plugin key; skipped.")
            continue

        bypassed = plugin.get("bypass", False)
        if handler.emitter is None:
            if bypassed and handler.silent_if_bypassed:
                continue
            if handler.skip_warning is None:
                raise RuntimeError(
                    f"{key}: dispatch entry has neither emitter nor "
                    "skip_warning")
            warn(handler.skip_warning)
            continue

        if bypassed:
            # Surface bypass-skip uniformly so users notice if their EE
            # bypassed-plugin choice silently disappeared — unless
            # silent_if_bypassed marks bypass as the expected default
            # (autogain on HDA), where nagging would be noise.
            if not handler.silent_if_bypassed:
                warn(f"{key}: bypassed in source preset; not emitted.")
            continue

        if key == "convolver#0":
            stage = handler.emitter(plugin, irs_dir, *handler.args,
                                    must_exist=must_exist)
        else:
            stage = handler.emitter(plugin, *handler.args)
        if stage is not None:
            result.stages.append(stage)
            for w in stage.warnings:
                warn(w)

    # The loop above only visits plugins_order — a plugin object that never
    # made it into the order (hand-edited preset) would vanish without this.
    orphaned = [k for k, v in out.items()
                if k not in ("blocklist", "plugins_order")
                and isinstance(v, dict) and k not in plugins_order]
    for key in sorted(orphaned):
        warn(f"{key}: present in preset output but missing from "
             "plugins_order; not emitted.")

    return result


def emit_links(stages: list[Stage]) -> list[dict]:
    """Generate stereo pair-wise links between adjacent stages."""
    links = []
    for prev, nxt in zip(stages, stages[1:]):
        links.append({
            "output": f"{prev.out_l[0]}:{prev.out_l[1]}",
            "input": f"{nxt.in_l[0]}:{nxt.in_l[1]}",
        })
        links.append({
            "output": f"{prev.out_r[0]}:{prev.out_r[1]}",
            "input": f"{nxt.in_r[0]}:{nxt.in_r[1]}",
        })
    return links


# ---------------------------------------------------------------------------
# SPA-JSON formatter
# ---------------------------------------------------------------------------

# Bare-key tokens (PipeWire SPA-JSON allows these unquoted)
_BARE_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_.\-]*$")


def _fmt_num(v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        # Ten significant figures preserves EE's 4-decimal precision on
        # values up to ~1e6 (e.g. attack-time 649.4292 ms) without
        # lapsing into scientific notation. Trailing zeros are dropped
        # by %g.
        s = f"{v:.10g}"
        # Avoid emitting `inf`/`nan` — clamp to a representable value
        # so the conf still parses.
        if s in ("inf", "-inf", "nan"):
            return "0.0"
        return s
    raise TypeError(f"_fmt_num: unsupported type {type(v).__name__}")


def _fmt_value(v, indent: int) -> str:
    if v is None:
        return "null"
    if isinstance(v, (bool, int, float)):
        return _fmt_num(v)
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, list):
        return "[ " + " ".join(_fmt_value(x, indent) for x in v) + " ]"
    if isinstance(v, dict):
        return _fmt_dict(v, indent)
    raise TypeError(f"_fmt_value: unsupported type {type(v).__name__}")


def _fmt_key(k: str) -> str:
    return k if _BARE_KEY_RE.match(k) else json.dumps(k)


def _fmt_dict(d: dict, indent: int) -> str:
    pad = "    " * (indent + 1)
    closing = "    " * indent
    lines = []
    for k, v in d.items():
        lines.append(f"{pad}{_fmt_key(k)} = {_fmt_value(v, indent + 1)}")
    return "{\n" + "\n".join(lines) + "\n" + closing + "}"


def format_conf(stages: list[Stage], links: list[dict],
                node_name: str, node_description: str,
                target_object: str | None = None,
                target_sink: str | None = None,
                warnings: list[str] | None = None) -> str:
    """Render the full PipeWire filter-chain conf as text.

    ``target_sink`` (the WirePlumber 0.5+ smart-filter target — typically
    the internal speaker sink's ``node.name``) makes the chain attach
    transparently to that hardware sink: apps keep targeting the
    speaker sink as the default, WirePlumber's link resolver routes
    them through the filter automatically, the chain auto-bypasses on
    HDMI/Bluetooth/USB, and there's no second volume layer. When unset,
    falls back to the v1 virtual-sink behaviour.

    ``target_object`` is the lower-level "pin playback to this node"
    used by the measurement rig to redirect into a null sink; it
    coexists with ``target_sink`` but the smart-filter pattern usually
    makes it unnecessary outside test rigs.
    """
    if not stages:
        msg = (
            "cannot format conf with empty stage list (every plugin was "
            "either bypassed in the source preset or in the v1 cuts list)"
        )
        if warnings:
            msg += "; warnings collected during build:\n  - " + \
                "\n  - ".join(warnings)
        raise ValueError(msg)
    nodes = [n for s in stages for n in s.nodes]
    # Without explicit `inputs` / `outputs`, the filter.graph has no
    # external endpoints and PipeWire silently passes nothing through —
    # audio reaches the capture sink but never enters the graph. The
    # first stage's input ports become the chain's audio inputs; the
    # last stage's output ports become its audio outputs.
    first, last = stages[0], stages[-1]
    graph_inputs = [f"{first.in_l[0]}:{first.in_l[1]}",
                    f"{first.in_r[0]}:{first.in_r[1]}"]
    graph_outputs = [f"{last.out_l[0]}:{last.out_l[1]}",
                     f"{last.out_r[0]}:{last.out_r[1]}"]
    safe_name = _sanitize_name(node_name)
    capture_props: dict = {
        "node.name": f"effect_input.{safe_name}",
        "media.class": "Audio/Sink",
    }
    if target_sink:
        # Smart-filter mode: WirePlumber 0.5+'s linking pipeline
        # (linking/find-filter-target.lua + linking/get-filter-from-target.lua)
        # detects nodes with `filter.smart = true` plus a matching
        # `filter.smart.target` and inserts them on links targeting that
        # node. `node.link-group` ties the capture and playback streams
        # together as one logical filter so WP routes them as a unit.
        # `filter.smart.targetable` defaults to false, which keeps apps
        # from picking the chain's capture sink directly — they target
        # the hardware speaker sink as usual, the chain inserts itself
        # in the path. No second volume layer; HDMI/BT outputs aren't
        # matched, so the chain bypasses automatically when audio
        # routes anywhere other than ``target_sink``.
        #
        # `priority.session = -1` keeps WirePlumber's
        # default-nodes/find-best-default-node.lua from picking the
        # chain as the default sink (it would otherwise win the
        # tiebreaker against the speaker sink — both have priority 0
        # by default, and the freshly-loaded chain sorts later). With
        # smart-filter routing, the user wants the speaker sink to
        # remain the default; the chain inserts itself transparently.
        capture_props.update({
            "node.link-group": f"{safe_name}{DEFAULT_LINK_GROUP_SUFFIX}",
            "filter.smart": True,
            "filter.smart.name": safe_name,
            "filter.smart.target": {"node.name": target_sink},
            "priority.session": -1,
        })
    playback_props: dict = {
        "node.name": f"effect_output.{safe_name}",
        "node.passive": True,
    }
    if target_sink:
        # Same link-group on the playback side so WirePlumber treats the
        # capture and playback streams as one filter for routing.
        playback_props["node.link-group"] = (
            f"{safe_name}{DEFAULT_LINK_GROUP_SUFFIX}"
        )
    args = {
        "node.description": node_description,
        "media.name": node_description,
        "filter.graph": {
            "nodes": nodes,
            "links": links,
            "inputs": graph_inputs,
            "outputs": graph_outputs,
        },
        "audio.channels": 2,
        "audio.position": ["FL", "FR"],
        "capture.props": capture_props,
        "playback.props": playback_props,
    }
    if target_object:
        # Bind the playback stream to a specific downstream sink. Used
        # by the measurement tooling to route the chain into a null
        # sink (e.g. ee_capture) instead of the system default — without
        # this, WirePlumber auto-links to the actual speakers.
        args["playback.props"]["target.object"] = target_object
    module = {"name": "libpipewire-module-filter-chain", "args": args}
    body = (
        f"{CONF_HEADER_MARK} — see\n"
        "# https://github.com/antoinecellerier/speaker-tuning-to-easyeffects\n"
        f"# version: {version.get_version()}\n"
        "#\n"
        "# IRS file paths are absolute. By default the converter copies\n"
        "# the .irs next to this conf, so the chain is self-contained;\n"
        "# re-run ee_to_pipewire.py to refresh after updating the source\n"
        "# EasyEffects preset.\n\n"
        "context.modules = [\n"
    )
    body += "    " + _fmt_dict(module, 1) + "\n"
    body += "]\n"
    return body
