#!/usr/bin/env python3
"""Capture the DAX3 stimulus battery through a PipeWire filter-chain
generated by `ee_to_pipewire.py`.

Sibling to `tools/measure_ee/capture_battery.py` (which captures the
live EasyEffects chain). Both write `loopback_<stim>_<label>.{wav,
json}` in the same schema so `tools/measure_dax/analyze.py` and the
comparison tooling treat them interchangeably.

Pre-flight (the easy way — let `setup_chain.sh` do steps 1-4):

    bash tools/measure_ee/setup_null_sink.sh
    bash tools/measure_pw/setup_chain.sh \\
        ~/.local/share/easyeffects/output/Dolby-Balanced.json \\
        Dolby_PW_Test
    python3 tools/measure_pw/capture_battery.py \\
        --node-name Dolby_PW_Test --label pw_dolby_balanced

Equivalent manual sequence:
  1. Generate the conf:
        python3 ee_to_pipewire.py <ee-preset>.json \\
            --output ~/.config/pipewire/filter-chain.conf.d/<NAME>.conf \\
            --node-name <NAME> --target-object ee_capture --force
  2. Start it as a child PipeWire instance:
        pipewire -c filter-chain.conf &
     (Daemonised via your shell of choice; keep the PID for teardown.)
  3. Set up the same null-sink route used by EE captures:
        bash tools/measure_ee/setup_null_sink.sh
     (Loads `ee_capture`. We re-use it as the capture target so the
     analyzer treats EE and PW captures identically.)
  4. Wire the chain's playback into the null sink, set chain as
     default sink, stop EasyEffects (so its sink doesn't get
     auto-linked into the chain output, see setup_chain.sh).
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

import numpy as np
from scipy.io import wavfile

SR = 48000
SCHEMA_VERSION = 1

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
DEFAULT_STIMULUS_DIR = REPO_ROOT / "localresearch" / "measure_ee" / "stimuli"
DEFAULT_OUT_DIR = REPO_ROOT / "localresearch" / "measure_pw" / "captures"
# Re-use the play_and_capture primitive from tools/measure_ee/smoke.py
# so playback timing stays identical between EE and PW captures.
sys.path.insert(0, str(SCRIPT_DIR.parent / "measure_ee"))
import smoke as _smoke  # noqa: E402

STIMULUS_NAMES = (
    "stimulus_sweep.wav",
    "stimulus_sweep_quiet.wav",
    "stimulus_pink.wav",
    "stimulus_pink_quiet.wav",
    "stimulus_multitone.wav",
)


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _stimulus_meta(stim_path: Path) -> dict:
    meta_path = stim_path.with_suffix(".json")
    if not meta_path.is_file():
        raise SystemExit(
            f"missing stimulus meta JSON: {meta_path} — re-run "
            f"tools/measure_dax/make_stimulus.py to generate it"
        )
    return json.loads(meta_path.read_text())


def _capture_metrics(cap: np.ndarray) -> dict:
    if cap.ndim == 1:
        cap = np.column_stack([cap, cap])
    rms = np.sqrt(np.mean(cap.astype(np.float64) ** 2, axis=0))
    peak = np.max(np.abs(cap), axis=0)
    return {
        "samples": int(cap.shape[0]),
        "duration_seconds": float(cap.shape[0] / SR),
        "channels": int(cap.shape[1]),
        "sample_rate_hz": SR,
        "peak_per_channel": [float(p) for p in peak],
        "rms_per_channel": [float(r) for r in rms],
    }


def _pipewire_version() -> str | None:
    try:
        rc = subprocess.run(
            ["pipewire", "--version"], capture_output=True, text=True, timeout=2,
        )
        return rc.stdout.strip() or None
    except Exception:
        return None


def _platform_str() -> str:
    import platform
    return platform.platform()


def _check_chain_present(node_name: str) -> bool:
    """Confirm the filter-chain's input sink is registered with PipeWire."""
    try:
        rc = subprocess.run(
            ["pw-cli", "ls", "Node"], capture_output=True, text=True, timeout=4,
        )
    except FileNotFoundError:
        return False
    return f"effect_input.{node_name}" in rc.stdout


def capture_one(
    stim_path: Path, target: str, out_path: Path,
    label: str, node_name: str, verbose: bool,
) -> None:
    meta = _stimulus_meta(stim_path)
    stim_kind = meta.get("kind") or "sweep"
    stim_tag = stim_path.stem.replace("stimulus_", "", 1) or stim_kind

    play_target = f"effect_input.{node_name}"
    _smoke.play_and_capture(
        stim_path=stim_path,
        target=target,
        capture_path=out_path,
        play_target=play_target,
        verbose=verbose,
    )
    if not out_path.is_file() or out_path.stat().st_size == 0:
        raise SystemExit(f"capture failed (no data): {out_path}")

    sr, cap = wavfile.read(str(out_path))
    if sr != SR:
        print(f"WARN: capture sr={sr} != expected {SR}", file=sys.stderr)
    if cap.dtype == np.int16:
        cap_f = cap.astype(np.float32) / 32768.0
    elif cap.dtype == np.int32:
        cap_f = cap.astype(np.float32) / 2147483648.0
    elif cap.dtype == np.float32:
        cap_f = cap
    else:
        cap_f = cap.astype(np.float32)

    sidecar = {
        "schema_version": SCHEMA_VERSION,
        "capture_source": "pipewire_filter_chain",
        "timestamp_utc": datetime.datetime.now(
            datetime.timezone.utc
        ).isoformat(),
        "label": label,
        "stimulus_tag": stim_tag,
        "stimulus_kind": stim_kind,
        "wav_filename": out_path.name,
        "endpoint": {
            "name": target,
            "node": play_target,
            "filter_chain_node_name": node_name,
        },
        "stimulus": {
            "path": str(stim_path),
            "sample_rate_hz": SR,
            "channels": 2,
            "sha256": _sha256_file(stim_path),
            "sweep_seconds": meta.get("sweep_seconds"),
            "tail_seconds": meta.get("tail_seconds"),
            "stimulus_meta": meta,
        },
        "capture": _capture_metrics(cap_f),
        "system": {
            "platform": _platform_str(),
            "python_version": sys.version.split()[0],
            "pipewire_version": _pipewire_version(),
        },
    }
    out_path.with_suffix(".json").write_text(
        json.dumps(sidecar, indent=2, default=str)
    )
    if verbose:
        print(f"wrote {out_path} + sidecar")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--stimulus-dir", type=Path, default=DEFAULT_STIMULUS_DIR,
                    help=f"Directory containing stimulus_*.{{wav,json}} "
                         f"(default: {DEFAULT_STIMULUS_DIR})")
    ap.add_argument("--node-name", required=True,
                    help="Filter-chain node name (the value passed to "
                         "ee_to_pipewire.py --node-name; must match the "
                         "currently-loaded chain)")
    ap.add_argument("--label", required=True,
                    help='Output filename label (e.g. "pw_dolby_balanced")')
    ap.add_argument("--target", default="ee_capture.monitor",
                    help="PipeWire capture node (default ee_capture.monitor; "
                         "assumes the chain's output is wired into ee_capture)")
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR,
                    help=f"output directory for loopback wavs "
                         f"(default: {DEFAULT_OUT_DIR})")
    ap.add_argument("--stimuli", nargs="*",
                    help="Subset of stimulus filenames "
                         "(default all 5 in stimulus-dir)")
    ap.add_argument("-v", "--verbose", action="store_true")
    args = ap.parse_args()

    if shutil.which("pw-cat") is None or shutil.which("pw-record") is None:
        print("ERROR: pw-cat / pw-record not in PATH", file=sys.stderr)
        return 2
    if not _check_chain_present(args.node_name):
        print(f"ERROR: PipeWire node 'effect_input.{args.node_name}' not "
              "found. Did you load the filter-chain? See module docstring.",
              file=sys.stderr)
        return 2

    args.out_dir.mkdir(parents=True, exist_ok=True)

    if args.stimuli:
        stim_files = [args.stimulus_dir / s for s in args.stimuli]
    else:
        stim_files = [args.stimulus_dir / s for s in STIMULUS_NAMES]
    missing = [str(s) for s in stim_files if not s.is_file()]
    if missing:
        print(f"ERROR: missing stimulus files: {missing}", file=sys.stderr)
        return 2

    print(f"=== capturing battery, chain={args.node_name!r} ===")
    for stim in stim_files:
        tag = stim.stem.replace("stimulus_", "", 1)
        out_path = args.out_dir / f"loopback_{tag}_{args.label}.wav"
        print(f"[{tag}] capturing -> {out_path.name}")
        t0 = time.monotonic()
        capture_one(stim, args.target, out_path, args.label, args.node_name,
                    verbose=args.verbose)
        print(f"  done in {time.monotonic() - t0:.1f} s")

    print()
    print(f"battery complete. {len(stim_files)} captures in {args.out_dir}")
    print("next: tools/measure_pw/compare_ee_vs_pw.py to overlay against EE")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
